from django.urls import include, path
from rest_framework.routers import DefaultRouter

from apps.employment.views import JobVacancyViewSet

# Create a DefaultRouter instance
router = DefaultRouter()

# Register the JobVacancyViewSet view set with the router.
# This maps the view set to the URL pattern 'vacancies/' and assigns the name 'vacancies' to the URL pattern.
router.register('vacancies', JobVacancyViewSet, 'vacancies')

# Define urlpatterns for the Django application
urlpatterns = [
    # Include the URLs generated by the router in the main URL patterns
    path('', include(router.urls)),
]
